- platform: mqtt
  name: "Zac Phone MQTT status"
  state_topic: !secret mqtt_topic_status_zac
  payload_on: "1"
  payload_off: "0"
  sensor_class: connectivity
- platform: mqtt
  name: "Tegan Phone MQTT status"
  state_topic: !secret mqtt_topic_status_tegan
  payload_on: "1"
  payload_off: "0"
  sensor_class: connectivity
- platform: mqtt
  name: "Wallpanel MQTT status"
  state_topic: !secret mqtt_topic_status_wallpanel
  payload_on: "1"
  payload_off: "0"
  sensor_class: connectivity
