- platform: generic
  name: Street View Tegan
  still_image_url: https://maps.googleapis.com/maps/api/streetview?size=600x300&location={{states.device_tracker.tegan_nexus_6p.attributes.latitude}},{{states.device_tracker.tegan_nexus_6p.attributes.longitude}}&key={{states.sensor.google_streetview_api_key.state}}
  limit_refetch_to_url_change: true
- platform: generic
  name: Street View Zac
  still_image_url: https://maps.googleapis.com/maps/api/streetview?size=600x300&location={{states.device_tracker.zac_nexus_6p.attributes.latitude}},{{states.device_tracker.zac_nexus_6p.attributes.longitude}}&key={{states.sensor.google_streetview_api_key.state}}
  limit_refetch_to_url_change: true
- platform: generic
  name: Map Location
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{states.sensor.center_map_on.state}}&zoom={{states.input_number.map_zoom.state|int}}&size=600x300&maptype=roadmap&{{states.sensor.map_markers.state}}&key={{states.sensor.google_staticmap_api_key.state}}
  limit_refetch_to_url_change: true
