#########################################
#The main configuration.yaml - see my   #
#README.md for information on how I have#
#structured and organised this file     #
#and the !include files that it links to#
#########################################

##################
## Core program ##
##################
homeassistant: !include config/core/homeassistant.yaml
logger: !include config/core/logger.yaml

###################################
## Web interface UX and security ##
###################################
frontend:
config:
group: !include config/interface/group.yaml
http: !include config/interface/http.yaml
history:
logbook: !include config/interface/logbook.yaml
discovery:
panel_custom: !include config/interface/panel_custom.yaml
zone: !include config/interface/zone.yaml

#######################################
## My components/devices/sensors/etc ##
#######################################
updater:
  include_used_components: true
arlo:
  username: !secret arlo_username
  password: !secret arlo_password
ffmpeg:
camera: !include_dir_merge_list config/component/camera
alarm_control_panel: !include_dir_merge_list config/component/alarm_control_panel
sensor: !include_dir_merge_list config/component/sensor
switch: !include_dir_merge_list config/component/switch
climate: !include_dir_merge_list config/component/climate
tts: !include_dir_merge_list config/component/tts
light: !include_dir_merge_list config/component/light
media_player: !include_dir_merge_list config/component/media_player
device_tracker: !include_dir_merge_list config/component/device_tracker
binary_sensor: !include_dir_merge_list config/component/binary_sensor
notify: !include_dir_merge_list config/component/notify
google_assistant: !include_dir_merge_named config/component/google_assistant

#######################################
## My automations/scripts/scenes/etc ##
#######################################
automation: !include_dir_merge_list config/etc/automation
script: !include_dir_merge_named config/etc/script
input_boolean: !include config/etc/input_boolean.yaml
input_number: !include config/etc/input_number.yaml
