- platform: broadlink
  name: Broadlink Lounge Room
  update_interval: 60
  host: !secret broadlink_lounge_room_host
  mac: !secret broadlink_lounge_room_mac
  monitored_conditions:
    - temperature
