- platform: google_travel_time
  name: Zac to work
  api_key: !secret google_travel_time_api_key
  origin: device_tracker.zac_nexus_6p
  destination: !secret google_travel_time_work
- platform: google_travel_time
  name: Zac to home
  api_key: !secret google_travel_time_api_key
  origin: device_tracker.zac_nexus_6p
  destination: !secret google_travel_time_home
- platform: google_travel_time
  name: Tegan to work
  api_key: !secret google_travel_time_api_key
  origin: device_tracker.tegan_nexus_6p
  destination: !secret google_travel_time_work
- platform: google_travel_time
  name: Tegan to home
  api_key: !secret google_travel_time_api_key
  origin: device_tracker.tegan_nexus_6p
  destination: !secret google_travel_time_home
- platform: google_travel_time
  api_key: !secret google_travel_time_api_key
  name: Tegan to Zac
  origin: device_tracker.tegan_nexus_6p
  destination: device_tracker.zac_nexus_6p
- platform: google_travel_time
  api_key: !secret google_travel_time_api_key
  name: Zac to Tegan
  origin: device_tracker.zac_nexus_6p
  destination: device_tracker.tegan_nexus_6p
