- platform: haveibeenpwned
  email:
    - !secret haveibeenpwned_email_0
    - !secret haveibeenpwned_email_1
    - !secret haveibeenpwned_email_2
    - !secret haveibeenpwned_email_3
    - !secret haveibeenpwned_email_4
    - !secret haveibeenpwned_email_5
    - !secret haveibeenpwned_email_6
    - !secret haveibeenpwned_email_7
