- platform: sonarr
  api_key: !secret sonarr_api_key
  host: !secret sonarr_host
  port: !secret sonarr_port
  urlbase: !secret sonarr_urlbase
  monitored_conditions:
    - series
    - upcoming
    - wanted
    - queue
    - commands
    - diskspace
