- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /
  - type: disk_use
    arg: /
  - type: disk_free
    arg: /
  - type: memory_use_percent
  - type: memory_use
  - type: memory_free
  - type: processor_use
  - type: last_boot
  - type: since_last_boot
  - type: network_in
    arg: !secret systemmonitor_network_interface
  - type: network_out
    arg: !secret systemmonitor_network_interface
