project_id: !secret google_assistant_project_id
client_id: !secret google_assistant_client_id
access_token: !secret google_assistant_access_token
agent_user_id: !secret google_assistant_agent_user_id
api_key: !secret google_assistant_api_key
exposed_domains:
  - !secret google_assistant_exposed_domains_1
  - !secret google_assistant_exposed_domains_2
