api_password: !secret http_api_password
server_port: !secret http_server_port
cors_allowed_origins:
  - !secret http_cors_allowed_origins_1
  - !secret http_cors_allowed_origins_2
use_x_forwarded_for: True
trusted_proxies:
  - 127.0.0.1
  - ::1
trusted_networks:
  - !secret http_trusted_networks_1
  - !secret http_trusted_networks_2
  - !secret http_trusted_networks_3
ip_ban_enabled: True
login_attempts_threshold: !secret http_login_attempts_threshold
