  exclude:
    entities:
      - sun.sun
      - sensor.processor_use
      - sensor.disk_use_percent_
      - sensor.disk_free_
      - sensor.disk_use_
      - sensor.memory_use_percent
      - sensor.memory_free
      - sensor.memory_use
      - sensor.network_in_enxb827eb6629fc
      - sensor.network_out_enxb827eb6629fc
      - sensor.last_boot
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - sensor.sabnzbd_disk
      - sensor.sabnzbd_disk_free
      - sensor.sabnzbd_left
      - sensor.sabnzbd_queue
      - sensor.sabnzbd_speed
      - sensor.sabnzbd_status
      - sensor.transmission_down_speed
      - sensor.transmission_down_speed_kbps
      - sensor.transmission_status
      - sensor.transmission_up_speed
      - sensor.transmission_up_speed_kbps
      - sensor.transmission_turtle_mode
      - sensor.transmission_active_torrents
      - sensor.pws_weather_1d_metric
      - sensor.pws_weather_2d_metric
      - sensor.pws_weather_3d_metric
      - sensor.pws_weather_4d_metric
      - sensor.pws_temp_low_1d_c
      - sensor.pws_temp_high_1d_c
      - sensor.pws_temp_c
      - binary_sensor.tegan_phone_mqtt_status
      - binary_sensor.wallpanel_mqtt_status
      - binary_sensor.zac_phone_mqtt_status
