- platform: broadlink
  name: Sony TV
  host: !secret broadlink_mini_host
  mac: !secret broadlink_mini_mac
  ircodes_ini: 'config/component/media_player/broadlink_media_codes/sony_tv.ini'
  ping_host: !secret broadlink_sony_tv_ping_host
