- platform: broadlink
  name: Sony TV
  host: !secret broadlink_living_room_host
  mac: !secret broadlink_living_room_mac
  ircodes_ini: 'config/component/media_player/broadlink_media_codes/sony_tv.ini'
  ping_host: !secret broadlink_sony_tv_ping_host
- platform: broadlink
  name: LG TV
  host: !secret broadlink_lounge_room_host
  mac: !secret broadlink_lounge_room_mac
  ircodes_ini: 'config/component/media_player/broadlink_media_codes/lg_tv.ini'
  ping_host: !secret broadlink_lg_tv_ping_host
