# Change Google Music Playlist on playing chromecast
- alias: 'Change Google Music Playlist'
  trigger:
    platform: state
    entity_id: input_select.google_music_playlist
  condition:
    condition: or
    conditions:
     - condition: template
       value_template: '{{ is_state("input_select.chromecast_audio_device_internal", "lounge_group") and is_state("media_player.lounge_group", "playing") }}'
     - condition: template
       value_template: '{{ is_state("input_select.chromecast_audio_device_internal", "lounge_assistant") and is_state("media_player.lounge_assistant", "playing") }}'
     - condition: template
       value_template: '{{ is_state("input_select.chromecast_audio_device_internal", "lounge_soundbar") and is_state("media_player.lounge_soundbar", "playing") }}'
     - condition: template
       value_template: '{{ is_state("input_select.chromecast_audio_device_internal", "kitchen_group") and is_state("media_player.kitchen_group", "playing") }}'
     - condition: template
       value_template: '{{ is_state("input_select.chromecast_audio_device_internal", "kitchen_assistant") and is_state("media_player.kitchen_assistant", "playing") }}'
     - condition: template
       value_template: '{{ is_state("input_select.chromecast_audio_device_internal", "kitchen_speaker") and is_state("media_player.kitchen_speaker", "playing") }}'
     - condition: template
       value_template: '{{ is_state("input_select.chromecast_audio_device_internal", "assistant_group") and is_state("media_player.assistant_group", "playing") }}'
     - condition: template
       value_template: '{{ is_state("input_select.chromecast_audio_device_internal", "whole_home") and is_state("media_player.whole_home", "playing") }}'
  action:
    service: script.google_music_switch_playlist
