- alias: 'Change Radio Volume'
  trigger:
    platform: state
    entity_id: input_number.volume_radio
  action:
    service: script.radio_volume

# Change Radio station on playing chromecast
- alias: 'Change Radio Station'
  trigger:
    platform: state
    entity_id: input_select.radio_station
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: '{{ is_state("input_select.chromecast_audio_device", "Kitchen Speaker") and is_state("media_player.lounge_group", "playing") }}'
      - condition: template
        value_template: '{{ is_state("input_select.chromecast_audio_device", "Lounge Assistant") and is_state("media_player.lounge_assistant", "playing") }}'
      - condition: template
        value_template: '{{ is_state("input_select.chromecast_audio_device", "Kitchen Soundbar") and is_state("media_player.kitchen_soundbar", "playing") }}'
      - condition: template
        value_template: '{{ is_state("input_select.chromecast_audio_device", "Kitchen") and is_state("media_player.kitchen_group", "playing") }}'
      - condition: template
        value_template: '{{ is_state("input_select.chromecast_audio_device", "Kitchen Assistant") and is_state("media_player.kitchen_assistant", "playing") }}'
      - condition: template
        value_template: '{{ is_state("input_select.chromecast_audio_device", "Kitchen Speaker") and is_state("media_player.kitchen_speaker", "playing") }}'
      - condition: template
        value_template: '{{ is_state("input_select.chromecast_audio_device", "Everywhere") and is_state("media_player.whole_home", "playing") }}'
  action:
    service: script.radio_play
