- alias: Update notifications
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    service: notify.pushbullet
    data_template: 
      title: 'New Home Assistant Release'
      target: !secret pushbullet_channel_homeassistant_updates
      message: "Home Assistant  {{ states.updater.updater.state }}  is now available."
