sensor:
  - platform: template
    sensors:

      dark_outside:
        value_template: >
          {% if is_state('input_boolean.sunset_offset' , 'on') %}true
          {% elif (states.sun.sun.attributes.elevation|int < 3) %}true
          {% elif ((states.sun.sun.attributes.elevation|int < 4.5) and (states.sensor.dark_sky_cloud_coverage.state|int > 80)) %}true
          {% elif ((states.sun.sun.attributes.elevation|int < 6.5) and (states.sensor.dark_sky_cloud_coverage.state|int > 85)) %}true
          {% elif (states.sensor.dark_sky_cloud_coverage.state|int > 90) %}true
          {% else %} false {% endif %}

      bad_weather:
        value_template: >
          {% if is_state('sensor.dark_sky_precip' , 'snow') %}snow
          {% elif ((states.sensor.dark_sky_daily_low_temperature.state|int < 4) and (states.sensor.dark_sky_dew_point.state|int < 6)
            and (states.sensor.dark_sky_wind_speed.state|int < 12) and (states.sensor.dark_sky_cloud_coverage.state|int < 20)
            and (states.sensor.dark_sky_humidity.state|int > 50)) %} frost
          {% elif (states.sensor.dark_sky_precip_intensity|int > 7) %} heavy_rain
          {% else %} clear {% endif %}
