notify:
  - name: DingoDailyHA
    platform: twitter
    consumer_key: !secret twitter_consumer_key
    consumer_secret: !secret twitter_consumer_secret
    access_token: !secret twitter_access_token
    access_token_secret: !secret twitter_access_token_secret

### Building out some Historical stats for tweeting. #####################
sensor:
  - platform: history_stats
    name: Flic Presses
    entity_id: group.flic
    state: 'on'
    type: count
    end: '{{ now() }}'
    duration:
      hours: 24

  - platform: history_stats
    name: LIFX Lights time
    entity_id: group.all_lights
    state: 'on'
    type: time
    end: '{{ now() }}'
    duration:
      hours: 24

script:
  tweet_engine:
    sequence:
      - service: notify.pushbullet
        data_template:
          title: 'New Twitter post'
          target: !secret pushbullet_channel_twitter_updates
          message: "{{ tweet }}"

      - service: notify.DingoDailyHA
        data_template:
          message: >-
            {{ tweet }} #IOT #SmartHome

automation:
  - alias: 'New Twitter follower!'
    hide_entity: True
    trigger:
      - platform: event
        event_type: new_follower

    action:
      - service: script.tweet_engine
        data_template:
          tweet: >-
            {% set handle = trigger.event.data.value1 %}
            {% set location = trigger.event.data.location %}
            {% set phrases = [
              "Thanks for the Follow " ~ handle ~ "! Chirp the Bird from " ~ location ~ "!!",
              "Hey " ~ handle ~ "Thanks for the Follow from " ~ location ~ " !",
              "Wanna know who is super cool? "~ handle ~" IS!!!",
            ] %}
            {% set hashtags = [
              "#ThanksForTheFollow",
              "#FollowBack",
              "#FollowMe",
              "(http://www.vmwareinfo.com/2017/11/building-digital-cuckoo-clock-with-home.html)"
            ] %}
            {{ phrases|random ~ " " ~ hashtags|random }}

  - alias: 'Closed Github Issue'
    hide_entity: True
    trigger:
      - platform: event
        event_type: closed_github

    action:
      - service: script.tweet_engine
        data_template:
          tweet: >-
            {% set repo = trigger.event.data.repo %}
            {% set issue = trigger.event.data.issue %}
            {% set issueurl = trigger.event.data.issueurl %}
            {% set phrases = [
              "New Code Alert: " ~ issue ~ "(" ~ issueurl ~ "). Repo: (https://github.com/Zac300/Home-Assistant-Config/commits/master) "
            ] %}
            {% set hashtags = [
              "#Github",
              "#HomeAutomation",
              "#SmartHomeCode"
            ] %}
            {{ phrases|random ~ " " ~ hashtags|random }}


  - alias: 'Random House stats'
    hide_entity: True
    trigger:
      - platform: time
        hours: '/4'
        minutes: 01
        seconds: 00

    action:
      - service: automation.turn_off
        entity_id: automation.random_house_stats
      - delay: '0{{ range(0,2) | random | int }}:{{ range(10,59) | random | int }}:00'
      - service: script.tweet_engine
        data_template:
          tweet: >
            {{ [
            "The number of #Flic presses today was {{states.sensor.flic_presses.state}}",
            "The #lifx lights where on for about {{states.sensor.lifx_lights_time.attributes.value}} yesterday.",
            "{{states.sensor.captured_today_frontyard.state}} frontdoor events were captured today by #Arlo.",
            "The Pi has been running for {{states.sensor.since_last_boot_templated.state}}",
            "I am running Home Assistant version {{states.sensor.current_version.state}} (https://github.com/Zac300/Home-Assistant-Config)",
            "#Arlo captured {{states.sensor.captured_today_backyard.state}} backyard events in the last 24 hours.",
            "Outside is {{states.sensor.dark_sky_temperature.state}}{{states.sensor.dark_sky_apparent_temperature.attributes.unit_of_measurement}}. Currently inside the temperature is {{states.sensor.broadlink_sensor_temperature.state}}{{states.sensor.broadlink_sensor_temperature.attributes.unit_of_measurement}}.",
            "My Average #iiNet internet speeds are Download: {{states.sensor.speedtest_download.state}} Mbit/s & Upload {{states.sensor.speedtest_upload.state}} Mbit/s. #NBN",
            "Home Assistant has been running for {{states.sensor.uptime.state}} days. (https://github.com/Zac300/Home-Assistant-Config)",
            "So far, I have prevented {{states.sensor.pihole_ads_blocked_today.state}} ads from hitting the network via Pi-hole! http://www.pi-hole.net",
            "Pi-hole (http://www.pi-hole.net) has serviced {{states.sensor.pihole_dns_queries_today.state}} DNS requests today! #Pi3 #Raspberry",
            ] | random + " #RandomStat"}}
      - service: automation.turn_on
        entity_id: automation.random_house_stats
