xiaomi_aqara:
  gateways:
    - key: !secret xiaomi_aqara_gatway_1_key
      mac: !secret xiaomi_aqara_gatway_1_mac
      host: !secret xiaomi_aqara_gatway_1_host

group:
  xiaomi:
    name: Xiaomi
    view: yes
    icon: mdi:github-face
    entities:
      - group.xiaomi_sensors

  xiaomi_sensors:
    name: Sensors
    entities:
      - light.gateway_light_7811dcb065a1
      - switch.plug_158d00019d4661
      - binary_sensor.switch_158d0001f41e1e
      - binary_sensor.door_window_sensor_158d0001f366fe
      - binary_sensor.door_window_sensor_158d0001b748b5
      - binary_sensor.door_window_sensor_158d0001b75f45
      - binary_sensor.door_window_sensor_158d0001c316c0
      - binary_sensor.door_window_sensor_158d0001b711dd
      - binary_sensor.motion_sensor_158d00016573cb
      - sensor.temperature_158d000201d596
      - sensor.humidity_158d000201d596

homeassistant:
  customize:
    light.gateway_light_7811dcb065a1:
      friendly_name: Xiaomi Gateway Light

    switch.plug_158d00019d4661:
      friendly_name: Xiaomi Plug

    binary_sensor.switch_158d0001f41e1e:
      friendly_name: Medication Button

    binary_sensor.door_window_sensor_158d0001f366fe:
      friendly_name: Hallway Door
      icon: mdi:door

    binary_sensor.door_window_sensor_158d0001b748b5:
      friendly_name: Lounge Window
      icon: mdi:window-closed

    binary_sensor.door_window_sensor_158d0001b75f45:
      friendly_name: Bedroom Window
      icon: mdi:window-closed

    binary_sensor.door_window_sensor_158d0001c316c0:
      friendly_name: Study Window
      icon: mdi:window-closed

    binary_sensor.door_window_sensor_158d0001b711dd:
      friendly_name: 2nd Bedroom Window
      icon: mdi:window-closed

    binary_sensor.motion_sensor_158d00016573cb:
      friendly_name: Garage Motion Sensor
      icon: mdi:garage

    sensor.temperature_158d000201d596:
      friendly_name: Living Room Temperature

    sensor.humidity_158d000201d596:
      friendly_name: Living Room Humidity

automation:
  - alias: Garage Motion Detected 
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d00016573cb
        from: 'off'
        to: 'on'
    action:
      - service: script.janet_speech_engine
        data:
          call_greeting: 1
          call_inform: 1
          CustomMessage: "Motion was detected in the Garage."

  - alias: 2nd Bedroom Window opened
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001b711dd
        from: 'off'
        to: 'on'
    action:
      - service: script.janet_speech_engine
        data:
          call_greeting: 1
          call_inform: 1
          CustomMessage: "the 2nd bedroom window was opened."

  - alias: Lounge Window opened
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001b748b5
        from: 'off'
        to: 'on'
    action:
      - service: script.janet_speech_engine
        data:
          call_greeting: 1
          call_inform: 1
          CustomMessage: "the lounge window was opened."

  - alias: Master Bedroom Window opened          
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001b75f45
        from: 'off'
        to: 'on'
    action:
      - service: script.janet_speech_engine
        data:
          call_greeting: 1
          call_inform: 1
          CustomMessage: "the master bedroom window was opened."

  - alias: Study Window opened
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001c316c0
        from: 'off'
        to: 'on'
    action:
      - service: script.janet_speech_engine
        data:
          call_greeting: 1
          call_inform: 1
          CustomMessage: "the study window was opened."
