chromecast_audio_pause:
  alias: Pause Audio on Chromecast
  sequence:
    service: media_player.media_play_pause
    data_template:
      entity_id: >
        {%- for device in states.media_player -%}
          {%- if device.name == states.input_select.chromecast_audio_device.state -%}
            {{ device.entity_id }}
          {%- endif -%}
        {%- endfor -%}
chromecast_audio_stop:
  alias: Stop Audio on Chromecast
  sequence:
    service: media_player.media_stop
    data_template:
      entity_id: >
        {%- for device in states.media_player -%}
          {%- if device.name == states.input_select.chromecast_audio_device.state -%}
            {{ device.entity_id }}
          {%- endif -%}
        {%- endfor -%}
chromecast_audio_volume:
  alias: Set Audio Volume on Chromecast
  sequence:
    service: media_player.volume_set
    data_template:
      entity_id: >
        {%- for device in states.media_player -%}
          {%- if device.name == states.input_select.chromecast_audio_device.state -%}
            {{ device.entity_id }}
          {%- endif -%}
        {%- endfor -%}
      volume_level: '{{  states.input_number.chromecast_audio_volume.state  }}'
chromecast_audio_next_track:
  alias: Goto next track on Chromecast
  sequence:
    service: media_player.media_next_track
    data_template:
      entity_id: >
        {%- for device in states.media_player -%}
          {%- if device.name == states.input_select.chromecast_audio_device.state -%}
            {{ device.entity_id }}
          {%- endif -%}
        {%- endfor -%}
chromecast_audio_previous_track:
  alias: Goto previous track on Chromecast
  sequence:
    service: media_player.media_previous_track
    data_template:
      entity_id: >
        {%- for device in states.media_player -%}
          {%- if device.name == states.input_select.chromecast_audio_device.state -%}
            {{ device.entity_id }}
          {%- endif -%}
        {%- endfor -%}
