watch_tv:
  sequence:
    - service: light.turn_off
      data:
        entity_id: group.lounge_hall
    - service: light.turn_on
      data:
        entity_id: light.window
    - service: light.turn_on
      data:
        entity_id: light.tv
    - service: homeassistant.turn_on
      entity_id: switch.arlec_switch_1
    - service: homeassistant.turn_on 
      entity_id: switch.arlec_switch_2
    - condition: state
      entity_id: media_player.lg_tv
      state: 'off'
    - service: media_player.turn_on
      entity_id: media_player.lg_tv
bedtime:
  sequence:
    - service: light.turn_off
      data:
        entity_id: group.lounge_hall
    - service: light.turn_on
      data:
        entity_id: light.hallway
        brightness: 65
    - service: light.turn_off
      data:
        entity_id: group.bedroom
    - service: light.turn_on
      data:
        entity_id: light.bedside_lamp
    - service: homeassistant.turn_off
      entity_id: switch.arlec_switch_1
    - service: homeassistant.turn_off
      entity_id: switch.arlec_switch_2
    - service: fan.turn_off
      data:
        entity_id: fan.lounge
    - service: homeassistant.turn_on 
      entity_id: switch.arlec_switch_3
    - condition: state
      entity_id: media_player.lg_tv
      state: 'on'
    - service: media_player.turn_off
      entity_id: media_player.lg_tv
morning:
  sequence:
    - service: light.turn_on
      data:
        entity_id: light.hallway
    - service: homeassistant.turn_off
      entity_id: switch.arlec_switch_3
living_room_watch_tv:
  sequence:
    - condition: state
      entity_id: media_player.sony_tv
      state: 'off'
    - service: media_player.turn_on
      entity_id: media_player.sony_tv
living_room_tv_volume_up:
  sequence:
    - service: media_player.volume_up
      entity_id: media_player.sony_tv
    - service: media_player.volume_up
      entity_id: media_player.sony_tv
    - service: media_player.volume_up
      entity_id: media_player.sony_tv
living_room_tv_volume_down:
  sequence:
    - service: media_player.volume_down
      entity_id: media_player.sony_tv
    - service: media_player.volume_down
      entity_id: media_player.sony_tv
    - service: media_player.volume_down
      entity_id: media_player.sony_tv
lounge_room_tv_volume_up:
  sequence:
    - service: media_player.volume_up
      entity_id: media_player.lg_tv
    - service: media_player.volume_up
      entity_id: media_player.lg_tv
    - service: media_player.volume_up
      entity_id: media_player.lg_tv
lounge_room_tv_volume_down:
  sequence:
    - service: media_player.volume_down
      entity_id: media_player.lg_tv
    - service: media_player.volume_down
      entity_id: media_player.lg_tv
    - service: media_player.volume_down
      entity_id: media_player.lg_tv
