watch_tv:
  sequence:
    - service: light.turn_off
      data:
        entity_id: group.lounge_hall
    - service: light.turn_on
      data:
        entity_id: light.window
    - service: light.turn_on
      data:
        entity_id: light.tv
    - service: broadlink.send_packet_10_0_0_168
      data:
        packet: 
          - !secret switch_arlec_1_command_on
          - !secret switch_arlec_2_command_on
bedtime:
  sequence:
    - service: light.turn_off
      data:
        entity_id: group.lounge_hall
    - service: light.turn_on
      data:
        entity_id: light.hallway
        brightness: 65
    - service: light.turn_on
      data:
        entity_id: light.bedside_lamp
    - service: broadlink.send_packet_10_0_0_168
      data:
        packet:
          - !secret switch_arlec_1_command_off
          - !secret switch_arlec_2_command_off
living_room_tv_turn_on:
  sequence:
   - service: input_boolean.turn_on
     data:
       entity_id: input_boolean.turn_on_living_room_tv
living_room_tv_turn_off:
  sequence:
   - service: input_boolean.turn_off
     data:
       entity_id: input_boolean.turn_on_living_room_tv
living_room_tv_power_toggle:
  sequence:
    - service: broadlink.send_packet_10_0_0_165
      data:
        packet:
          - 'JgCMAE0VJhQUFCYUFBQmFBMVEhUmFRIVEhUTFBMAA01MFiYVExQnFBMUJhUSFRIVJhUTFBMUExUSAANNTRUnFBIVJhUTFCYVEhUSFSYVExQSFRMUFQADS04UJhUSFSYVEhUmFRMUExQlFhIVExQUFBIAA05MFSYVEhUpEhMUJxQSFRMUJxQTFBMVEhUSAA0FAAAAAAAAAAAAAAAA'
living_room_tv_volume_up:
  sequence:
    - service: broadlink.send_packet_10_0_0_165
      data:
        packet:
          - 'JgBUAE0VExUlFRQUExQmFRMUEhUnFBEWEhUSFRIAA2JNFRIVJhUSFhAXJxMTFBEWJhUVEhMVEhUSAANhSxcSFSYVEhUSFSYVEhYSFCcUEhYSFRIVEgANBQAAAAA='
          - 'JgBUAE0VExUlFRQUExQmFRMUEhUnFBEWEhUSFRIAA2JNFRIVJhUSFhAXJxMTFBEWJhUVEhMVEhUSAANhSxcSFSYVEhUSFSYVEhYSFCcUEhYSFRIVEgANBQAAAAA='
          - 'JgBUAE0VExUlFRQUExQmFRMUEhUnFBEWEhUSFRIAA2JNFRIVJhUSFhAXJxMTFBEWJhUVEhMVEhUSAANhSxcSFSYVEhUSFSYVEhYSFCcUEhYSFRIVEgANBQAAAAA='
living_room_tv_volume_down:
  sequence:
    - service: broadlink.send_packet_10_0_0_165
      data:
        packet:
          - 'JgBUAEwVJhYlFRMVEBYnFRIVERUnFREWEhQTFRIAA05LFiYVJxURFRMVJRYPFxIVJxURFRIVEhYTAANOTBUlFScUEhYTFCUVExUTFCYVEhUSFRMUEwANBQAAAAA='
          - 'JgBUAEwVJhYlFRMVEBYnFRIVERUnFREWEhQTFRIAA05LFiYVJxURFRMVJRYPFxIVJxURFRIVEhYTAANOTBUlFScUEhYTFCUVExUTFCYVEhUSFRMUEwANBQAAAAA='
          - 'JgBUAEwVJhYlFRMVEBYnFRIVERUnFREWEhQTFRIAA05LFiYVJxURFRMVJRYPFxIVJxURFRIVEhYTAANOTBUlFScUEhYTFCUVExUTFCYVEhUSFRMUEwANBQAAAAA='