# Scripts to turn on/off all lights and set booleans to determine selected lifx
turn_all_lights_off:
  sequence:
    - service: homeassistant.turn_off
      data:
        entity_id: group.all_lights
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.all_lights
turn_all_lights_on:
  sequence:
    - service: homeassistant.turn_on
      data:
        entity_id: group.all_lights
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.all_lights
select_bedside_lamp:
  sequence:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.bedroom_selected
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.bedside_lamp_selected
    - service: light.toggle
      data:
        entity_id: light.bedside_lamp
    - delay:
        seconds: 0.5
    - service: light.toggle
      data:
        entity_id: light.bedside_lamp
    - delay:
        seconds: 0.5
    - service: light.turn_on
      data:
        entity_id: light.bedside_lamp
select_bedroom:
  sequence:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.bedside_lamp_selected
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.bedroom_selected
    - service: light.toggle
      data:
        entity_id: light.bedroom
    - delay:
        seconds: 0.5
    - service: light.toggle
      data:
        entity_id: light.bedroom
    - delay:
        seconds: 0.5
    - service: light.turn_on
      data:
        entity_id: light.bedroom
select_lounge:
  sequence:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.hallway_selected
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.lounge_selected
    - service: light.toggle
      data:
        entity_id: light.lounge
    - delay:
        seconds: 0.5
    - service: light.toggle
      data:
        entity_id: light.lounge
    - delay:
        seconds: 0.5
    - service: light.turn_on
      data:
        entity_id: light.lounge
select_hallway:
  sequence:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.lounge_selected
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.hallway_selected
    - service: light.toggle
      data:
        entity_id: light.hallway
    - delay:
        seconds: 0.5
    - service: light.toggle
      data:
        entity_id: light.hallway
    - delay:
        seconds: 0.5
    - service: light.turn_on
      data:
        entity_id: light.hallway
