switch.arlec_switch_1:
  google_assistant: true
  google_assistant_name: Christmas Tree
  google_assistant_type: light
switch.arlec_switch_2:
  google_assistant: true
  google_assistant_name: Fairy Lights
  google_assistant_type: light
switch.soundbar_toggle_input:
  google_assistant: false
switch.sony_tv_power_toggle:
  google_assistant: false
climate.sharp_split_system:
  google_assistant: true
  google_assistant_name: Sharp Split System
  google_assistant_type: climate
  aliases:
    - Living Room Air Conditioner
    - Living Room A C
    - Split System
script.watch_tv:
  google_assistant: true
  google_assistant_name: Watch TV
  google_assistant_type: script
  aliases:
    - Watch a movie
    - Couch time
    - Time to relax
script.bedtime:
  google_assistant: true
  google_assistant_name: Bedtime
  google_assistant_type: script
  aliases:
    - Time to sleep
    - Go to bed
script.watch_living_room_tv:
  google_assistant: true
  google_assistant_name: Watch Living Room TV
  google_assistant_type: script
  aliases:
    - Watch Sony TV
    - Dinner Time
script.turn_up_living_room_tv:
  google_assistant: true
  google_assistant_name: Turn Up Living Room TV
  google_assistant_type: script
  aliases:
    - Turn Up Sony TV
    - Louder Living Room TV
    - Louder Sony TV
    - Sony TV Up
    - Sony TV Louder
    - Sony TV Volume Up
    - Living Room TV Volume Up
    - Volume Up Sony TV
    - Volume Up Living Room TV
script.turn_down_living_room_tv:
  google_assistant: true
  google_assistant_name: Turn Down Living Room TV
  google_assistant_type: script
  aliases:
    - Turn Down Sony TV
    - Quieter Living Room TV
    - Quieter Sony TV
    - Sony TV Down
    - Sony TV Quieter
    - Sony TV Volume Down
    - Living Room TV Volume Down
    - Volume Down Sony TV
    - Volume Down Living Room TV