switch.arlec_switch_1:
  google_assistant: true
  google_assistant_name: Christmas Tree
  google_assistant_type: light
switch.arlec_switch_2:
  google_assistant: true
  google_assistant_name: Fairy Lights
  google_assistant_type: light
switch.soundbar_toggle_input:
  google_assistant: false
switch.sony_tv_power_toggle:
  google_assistant: false
climate.sharp_split_system:
  google_assistant: true
  google_assistant_name: Sharp Split System
  google_assistant_type: climate
  aliases:
    - Living Room Air Conditioner
    - Living Room A C
    - Split System
script.watch_tv:
  google_assistant: true
  google_assistant_name: Watch TV
  google_assistant_type: script
  aliases:
    - Watch a movie
    - Couch time
    - Time to relax
script.bedtime:
  google_assistant: true
  google_assistant_name: Bedtime
  google_assistant_type: script
  aliases:
    - Time to sleep
    - Go to bed
script.living_room_tv_power_toggle:
  google_assistant: false
script.living_room_tv_turn_on:
  google_assistant: true
  google_assistant_name: Living Room TV turn on
  google_assistant_type: script
  aliases:
    - Turn on Sony TV
    - Turn on Living Room TV
    - Watch Sony TV
    - Watch Living Room TV
    - Sony TV on
    - Living Room TV off
script.living_room_tv_turn_off:
  google_assistant: true
  google_assistant_name: Living Room TV turn off
  google_assistant_type: script
  aliases:
    - Turn off Sony TV
    - Turn off Living Room TV
    - Sony TV off
    - Living Room TV off
script.living_room_tv_volume_up:
  google_assistant: true
  google_assistant_name: Living Room TV volume up
  google_assistant_type: script
  aliases:
    - Turn Up Sony TV
    - Louder Living Room TV
    - Louder Sony TV
    - Sony TV up
    - Sony TV louder
    - Sony TV volume up
    - Living Room TV volume up
    - Volume up Sony TV
    - Volume up Living Room TV
script.living_room_tv_volume_down:
  google_assistant: true
  google_assistant_name: Living Room TV volume up
  google_assistant_type: script
  aliases:
    - Turn down Sony TV
    - Quieter Living Room TV
    - Quieter Sony TV
    - Sony TV down
    - Sony TV quieter
    - Sony TV volume down
    - Living Room TV volume down
    - Volume down Sony TV
    - Volume down Living Room TV