switch.arlec_switch_3:
  google_assistant: true
  google_assistant_name: Sound Machine
  google_assistant_type: switch
switch.soundbar_toggle_input:
  google_assistant: false
switch.sony_tv_power_toggle:
  google_assistant: false
switch.google_music:
  google_assistant: false
media_player.sony_tv:
  google_assistant: true
  google_assistant_name: Sony TV
  google_assistant_type: media_player
media_player.lg_tv:
  google_assistant: true
  google_assistant_name: LG TV
  google_assistant_type: media_player
climate.sharp_split_system:
  google_assistant: true
  google_assistant_name: Sharp Split System
  google_assistant_type: climate
  aliases:
    - Living Room Air Conditioner
    - Living Room A C
    - Split System
fan.lounge:
  google_assistant: true
  google_assistant_name: Lounge Fan
  google_assistant_type: fan
  aliases:
    - Fan
    - Lounge Room Fan
script.watch_tv:
  google_assistant: true
  google_assistant_name: Watch TV
  google_assistant_type: script
  aliases:
    - Watch a movie
    - Couch time
    - Time to relax
script.bedtime:
  google_assistant: true
  google_assistant_name: Bedtime
  google_assistant_type: script
  aliases:
    - Time to sleep
    - Go to bed
script.living_room_tv_volume_up:
  google_assistant: true
  google_assistant_name: Living Room TV volume up
  google_assistant_type: script
  aliases:
    - Turn up Sony TV
    - Louder Living Room TV
    - Louder Sony TV
    - Sony TV up
    - Sony TV louder
    - Sony TV volume up
    - Living Room TV volume up
    - Volume up Sony TV
    - Volume up Living Room TV
    - Increase Sony TV volume
    - Increase Living Room TV volume
script.living_room_tv_volume_down:
  google_assistant: true
  google_assistant_name: Living Room TV volume down
  google_assistant_type: script
  aliases:
    - Turn down Sony TV
    - Quieter Living Room TV
    - Quieter Sony TV
    - Sony TV down
    - Sony TV quieter
    - Sony TV volume down
    - Living Room TV volume down
    - Volume down Sony TV
    - Volume down Living Room TV
    - Decrease Sony TV volume
    - Decrease Living Room TV volume
script.lounge_room_tv_volume_up:
  google_assistant: true
  google_assistant_name: Lounge Room TV volume up
  google_assistant_type: script
  aliases:
    - Turn up LG TV
    - Louder Lounge Room TV
    - Louder LG TV
    - LG TV up
    - LG TV louder
    - LG TV volume up
    - Lounge Room TV volume up
    - Volume up LG TV
    - Volume up Lounge Room TV
    - Increase LG TV volume
    - Increase Lounge Room TV volume
script.lounge_room_tv_volume_down:
  google_assistant: true
  google_assistant_name: Lounge Room TV volume down
  google_assistant_type: script
  aliases:
    - Turn down LG TV
    - Quieter Lounge Room TV
    - Quieter LG TV
    - LG TV down
    - LG TV quieter
    - LG TV volume down
    - Lounge Room TV volume down
    - Volume down LG TV
    - Volume down Lounge Room TV
    - Decrease LG TV volume
    - Decrease Lounge Room TV volume
