sensor.google_staticmap_api_key:
  hidden: true
sensor.google_streetview_api_key:
  hidden: true
sensor.center_map_on:
  hidden: true
sensor.map_markers:
  hidden: true
binary_sensor.sleeping:
  icon: mdi:hotel
binary_sensor.sarge_away:
  icon: mdi:paw
sensor.since_last_boot_templated:
  icon: mdi:timetable
