- platform: gmusic
  user: !secret gmusic_user
  password: !secret gmusic_password
  device_id: !secret gmusic_device_id # http://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.login
  media_player: chromecast_audio_device # entity id of the input select used for mediaplayer
  playlist: music_playlist # entity id of the input select used for playlist
