- platform: gmusic
  user: !secret gmusic_user
  password: !secret gmusic_password
  device_id: !secret gmusic_device_id
  media_player: chromecast_audio_device_internal
  playlist: google_music_playlist
