radio_station:
  name: 'Select Radio Station:'
  options:
    - Fresh 92.7
    - Hit 107
    - Mix 102.3
    - Nova 919
    - Triple J
    - ABC Adelaide 891
    - ABC Grandstand
    - FIVEaa
chromecast_audio_device:
  name: 'Select Speaker(s):'
  options:
   - Kitchen Assistant
   - Kitchen Speaker
   - Kitchen Group
   - Lounge Assistant
   - Lounge Soundbar
   - Lounge Group
   - Whole Home
  initial: Kitchen Group
  icon: mdi:speaker-wireless
google_music_playlist:
  name: 'Select Playlist:'
  options:
   - " "   # Should be empty
center_map_on:
  name: Center Map On
  icon: mdi:account-multiple
  options:
    - Zac
    - Tegan
house_mode:
  name: House Mode
  icon: mdi:home
  initial: None
  options:
   - None
   - Morning
   - Watch Lounge TV
   - Watch Living TV
   - Bedtime
