all_lights:
  name: All Lights On/Off
  initial: off
lounge_selected:
  name: Lounge Selected
  initial: on
hallway_selected:
  name: Hallway Light Selected
  initial: off
kitchen_party_mode:
  name: Kitchen Party Mode
  initial: off
lounge_party_mode:
  name: Lounge Party Mode
  initial: off
push_notification_distance_tegan_to_zac:
  name: Send Notifications - Tegan to Zac
  icon: mdi:message-alert
